services:
  web:
    build: .
    container_name: barbersoft_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: barbersoft_db
    restart: always
    environment:
      MARIADB_DATABASE: barbersoft
      MARIADB_USER: barbersoft_user
      MARIADB_PASSWORD: barbersoft_pass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
