# Generated by Django 5.2.12 on 2026-04-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventadetalleproducto',
            old_name='subototal',
            new_name='subtotal',
        ),
    ]
