# Generated by Django 5.2.12 on 2026-04-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_uppercase_catalog_names'),
        ('ventas', '0002_rename_subototal_ventadetalleproducto_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name': 'Comision', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de comision'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la comision'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=85.0, max_digits=5, verbose_name='Porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='catalogos.metododepago', verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='catalogos.metododepago', verbose_name='Metodo de Pago'),
        ),
    ]
