# Generated by Django 5.2.13 on 2026-05-13 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_ticket_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de venta'),
        ),
    ]
